LANG = "en"

STRINGS = {
    "pick_lang": "Language / Язык:\n  1  English\n  2  Русский",
    "en": {
        "title": "ghTor",
        "connecting": "Connecting to Tor...",
        "port_found": "Port: {}",
        "tor_ok": "{}",
        "tor_not_found": "ERROR: Tor not found. Start Tor Browser or Tor Expert Bundle.",
        "tor_error": "ERROR: {}",
        "threads_ask": "Number of threads [10]: ",
        "creating_sessions": "Creating {} sessions...",
        "ready": "Ready. {} threads.",
        "connect_first": "Connect to Tor first.",
        "file_info": "File: {} links, {} already in DB, {} new",
        "file_empty": "File not found or empty: {}",
        "check_new_or_all": "Check [n]ew only or [a]ll? (n/a): ",
        "nothing_to_check": "Nothing to check.",
        "timeout_ask": "Timeout per attempt (sec) [{}]: ",
        "retries_ask": "Retries per site [{}]: ",
        "crawl_ask": "Crawl discovered links? (y/n) [y]: ",
        "tg_enabled": "Telegram: enabled",
        "tg_disabled": "Telegram: disabled",
        "threads_info": "Threads: {}, Timeout: {}s, Retries: {}, Crawl: {}",
        "checking_urls": "Checking {} URLs... Ctrl+C to stop",
        "stopped": "Stopped.",
        "batch_size_ask": "Batch size [100]: ",
        "bruteforce_info": "Brute force. Batch: {}, Threads: {}",
        "bruteforce_stop": "Ctrl+C to stop",
        "batch_header": "--- batch #{} ({} addresses) ---",
        "crawl_round": "--- crawl round #{}: {} new links ---",
        "crawled_links": "[{}] +{} new links crawled",
        "online_fmt": "[{}] ONLINE  {}ms  [{}] [{}]  {}",
        "offline_fmt": "[{}] OFFLINE  {}  {}ms  (x{})",
        "dup_fmt": " [DUP of {}]",
        "search_prompt": "Search: ",
        "search_title": "Search: '{}'",
        "found_title": "Found sites",
        "monitor_ask": "Check interval (sec) [300]: ",
        "monitor_started": "Monitor started. Checking every {}s.",
        "monitor_stopped": "Monitor stopped.",
        "auto_exported": "Auto-exported {} sites to {}",
        "circuit_rotated": "[circuit] Rotated at check #{}",
        "menu_header": "[Tor: {}, {} threads] [{} links] [monitor: {}]",
        "menu_1": "Connect to Tor",
        "menu_2": "Scan from file",
        "menu_3": "Brute force",
        "menu_4": "Search database",
        "menu_5": "Show found sites",
        "menu_6": "Monitor on/off",
        "menu_0": "Exit",
        "bye": "Bye.",
        "stats_fmt": "Checked: {}  |  Found: {}  |  Online: {}  |  Offline: {}  |  DB: {}  |  Queue: {}  |  Monitor: {}",
        "table_header": "  {:>4}  {:<8}  {:>7}  {:<5}  {:<14}  {:<30}  URL",
        "col_status": "Status",
        "col_ping": "Ping",
        "col_lang": "Lang",
        "col_cat": "Cat",
        "col_title": "Title",
        "empty": "(empty)",
        "on": "on",
        "off": "off",
        "connected": "connected",
        "not_connected": "not connected",
        "ignored_title": "Ignored (title filter): {}",
        "no_file_bruteforce": "No links file found. Use brute force (menu 3) to discover sites.",
    },
    "ru": {
        "title": "ghTor",
        "connecting": "Подключение к Tor...",
        "port_found": "Порт: {}",
        "tor_ok": "{}",
        "tor_not_found": "ОШИБКА: Tor не найден. Запустите Tor Browser или Tor Expert Bundle.",
        "tor_error": "ОШИБКА: {}",
        "threads_ask": "Количество потоков [10]: ",
        "creating_sessions": "Создаю {} сессий...",
        "ready": "Готово. {} потоков.",
        "connect_first": "Сначала подключитесь к Tor.",
        "file_info": "Файл: {} ссылок, {} уже в базе, {} новых",
        "file_empty": "Файл не найден или пуст: {}",
        "check_new_or_all": "Проверять [n]овые или [a]все? (n/a): ",
        "nothing_to_check": "Нечего проверять.",
        "timeout_ask": "Таймаут на попытку (сек) [{}]: ",
        "retries_ask": "Попыток на сайт [{}]: ",
        "crawl_ask": "Краулить найденные ссылки? (y/n) [y]: ",
        "tg_enabled": "Telegram: включён",
        "tg_disabled": "Telegram: выключен",
        "threads_info": "Потоки: {}, Таймаут: {}с, Попытки: {}, Краулинг: {}",
        "checking_urls": "Проверяю {} URL... Ctrl+C для остановки",
        "stopped": "Остановлено.",
        "batch_size_ask": "Размер пачки [100]: ",
        "bruteforce_info": "Брутфорс. Пачка: {}, Потоки: {}",
        "bruteforce_stop": "Ctrl+C для остановки",
        "batch_header": "--- пачка #{} ({} адресов) ---",
        "crawl_round": "--- краулинг раунд #{}: {} новых ссылок ---",
        "crawled_links": "[{}] +{} новых ссылок найдено",
        "online_fmt": "[{}] ОНЛАЙН  {}мс  [{}] [{}]  {}",
        "offline_fmt": "[{}] ОФЛАЙН  {}  {}мс  (x{})",
        "dup_fmt": " [ДУБ {}]",
        "search_prompt": "Поиск: ",
        "search_title": "Поиск: '{}'",
        "found_title": "Найденные сайты",
        "monitor_ask": "Интервал проверки (сек) [300]: ",
        "monitor_started": "Мониторинг запущен. Проверка каждые {}с.",
        "monitor_stopped": "Мониторинг остановлен.",
        "auto_exported": "Авто-экспорт: {} сайтов в {}",
        "circuit_rotated": "[circuit] Ротация на проверке #{}",
        "menu_header": "[Tor: {}, {} потоков] [{} ссылок] [мониторинг: {}]",
        "menu_1": "Подключиться к Tor",
        "menu_2": "Сканировать из файла",
        "menu_3": "Брутфорс",
        "menu_4": "Поиск по базе",
        "menu_5": "Показать найденные",
        "menu_6": "Мониторинг вкл/выкл",
        "menu_0": "Выход",
        "bye": "Пока.",
        "stats_fmt": "Проверено: {}  |  Найдено: {}  |  Онлайн: {}  |  Офлайн: {}  |  БД: {}  |  Очередь: {}  |  Мониторинг: {}",
        "table_header": "  {:>4}  {:<8}  {:>7}  {:<5}  {:<14}  {:<30}  URL",
        "col_status": "Статус",
        "col_ping": "Пинг",
        "col_lang": "Язык",
        "col_cat": "Кат",
        "col_title": "Заголовок",
        "empty": "(пусто)",
        "on": "вкл",
        "off": "выкл",
        "connected": "подключён",
        "not_connected": "не подключён",
        "ignored_title": "Игнорирован (фильтр заголовков): {}",
        "no_file_bruteforce": "Файл ссылок не найден. Используйте брутфорс (пункт 3) для поиска сайтов.",
    },
}


def set_lang(lang_code):
    global LANG
    LANG = lang_code


def t(key, *args):
    s = STRINGS.get(LANG, STRINGS["en"]).get(key, key)
    if args:
        return s.format(*args)
    return s